nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: <TOKEN>

npmPublishAccess: public

npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
  lstreckeisen:
    npmAlwaysAuth: true
    npmAuthToken: <TOKEN>
    npmPublishRegistry: "https://npm.pkg.github.com/lstreckeisen"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
