@startuml
abstract class AbstractSemanticTokenProvider

class ContextMapperDslSemanticTokenProvider {
# highlightElement(AstNode, SemanticTokenAcceptor)
}

class SemanticTokenProviderRegistry {
- semanticTokenProviders: Map<string, ContextMapperSemanticTokenProvider<AstNode>>
+ get(AstNode): ContextMapperSemanticTokenProvider<AstNode>
}

interface ContextMapperSemanticTokenProvider {
+ highlight(T, SemanticTokenAcceptor)
}

AbstractSemanticTokenProvider <|-- ContextMapperDslSemanticTokenProvider
ContextMapperDslSemanticTokenProvider --> SemanticTokenProviderRegistry
SemanticTokenProviderRegistry o-- "0..*" ContextMapperSemanticTokenProvider
@enduml