@startuml
abstract class ValidationRegistry {
+ register(ValidationChecks<T>, ThisParameterType)
}

class ContextMapperDslValidationRegistry {
}

class ContextMapperDslValidator {
+ validate(AstNode, ValidationAcceptor)
}

class ContextMapperValidationProviderRegistry {
- _providers: Map<string, ContextMapperValidationProvider<AstNode>>
+ get(AstNode): ContextMapperValidationProvider<AstNode>
}

interface ContextMapperValidationProvider {
+ validate(T, ValidationAcceptor)
}

ValidationRegistry <|-- ContextMapperDslValidationRegistry
ContextMapperDslValidationRegistry --> ContextMapperDslValidator
ContextMapperDslValidationRegistry --> ContextMapperValidationProviderRegistry
ContextMapperDslValidator --> ContextMapperValidationProviderRegistry
ContextMapperValidationProviderRegistry o-- "0..*" ContextMapperValidationProvider
@enduml