name: CML language server build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      # required since test report action uses git
      - name: Setup git
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          git config --global --add safe.directory "/__w/$REPO_NAME/$REPO_NAME"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Langium resources
        run: yarn langium:generate:production

      - name: Linting
        run: yarn lint

      - name: Langium Tests
        run: yarn test

      - name: Langium Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Langium Test Results
          path: out/test-results.xml
          reporter: java-junit

      - name: Build
        run: yarn build

      - name: Bundle
        run: yarn bundle:language-server

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
          args: --linter,jetbrains/qodana-js:2024.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_379728607 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      - name: Upload language server artifact
        uses: actions/upload-artifact@v4
        with:
          name: cml-language-server
          path: ./cml-ls/
